### ISSUE TITLE
Confusion in featurization tutorial

### ISSUE THREAD

**Issue by urwrstkn8mare** [tensorflow/recommenders#141]
Hi, I was a little confused in the section titled, "Defining the embeddings", in the [featurization tutorial](https://github.com/tensorflow/recommenders/blob/main/docs/examples/featurization.ipynb). There was a number of questions/issues/confusing things here.

1. It is written `# Let's use the hashing approach.` despite the `input_dim` using the `.vocab_size()` of the string lookup and the sequential model it uses `movie_title_lookup`, the variable with the string lookup (`movie_title_hashing` is the variable for the hashing approach). 
2. `user_id_lookup` is a string lookup but `input_dim` is assigned `num_hashing_bins`.

Sorry, but am I missing something or is it a mistake. I would appreciate any clarification. 

PS. I thought I would ask some questions while I'm at it: would you recommend using `Hashing()` or `StringLookup()` for the user and/or movie embeddings. If hashing what should be a good `num_hashing_bins` for a dataset like 25m in size. Is there a maximum number of bins I can use?

Thanks for any help in advance!

**Comment by maciejkula** [comment]
Thanks for pointing this out! You are correct that these are inconsistencies - I'll have a PR shortly to fix them.

When it comes to hashing vs explicit lookup, there are a couple of considerations to keep in mind. I note them down below, but a `StringLookup` layer with an explicit vocabulary for your most common tokens and a decently sized number of hashing bins for OOV items (`num_oov_indices`) is probably your best bet.

1. If you have a static vocabulary, using string lookup will likely improve the performance of your model due to the lack of hash collisions.
2. If you have a vocabulary that changes over time, and new tokens appear, having at least some buckets reserved for hashing is really useful - with them, your model can learn representations for the new tokens without restarting the training from scratch. This is very often the case with recommender models (say, new items or users appear).
3. For deciding the number of bins, you can do an empirical search (treat it as a hyperparameter and see how model metrics change), or decide on what hash collision probability is acceptable for you and run with that.

**Comment by urwrstkn8mare** [comment]
Thanks alot for that @maciejkula!

**Comment by maciejkula** [comment]
Thanks for finding the inconsistencies!
