### ISSUE TITLE
Memory Issues (due to excessive embedding vocabulary?)

### ISSUE THREAD

**Issue by SimonCW** [tensorflow/recommenders#324]
Hi, 

### Main Question
I am experimenting with the DCN model on my data. For smaller data samples the model trains fine, however, for larger datasets the memory (not GPU memory) of my machine runs full and crashes even before the the first training epoch starts when calling `fit()`. 

One suspicion I have is that the embedding vocabulary just gets too big, that would explain why the model crashes before the first epoch starts ... presumably during creation of the embeddings (which I assume happens on CPU). Is that a realistic cause of my memory issues or should I look elsewhere? Another source might be the fact, that I am loading my data from parquet in to numpy arrays and then creating a dataset with `.from_tensor_slices()`. I wanted to stream the data from parquet but I was having problems with shapes when doing this via tensorflow-io. Also, vocabulary creation is much harder when not having the full data in memory ... .

### Details
I'm using a p2.xlarge ec2 instance with 61 GB of memory. In my dataset, I have ~1.5 Mio Users and ~12k Items. Embedding dimension is 50. I've tried to embed the user and item ids with the hashing function and n_bins=200k but that didn't help.

### Side Questions
- When training with small enough data samples that don't have the above problem, I only see around 8% of GPU utilized (nvidia-smi). The main parameter to tweak here is the batch_size, right? However, if I increase the batch_size, also the memory consumption (not only GPU RAM) increases significantly.
- When using the hashing trick for 1.5 Mio users with 200k bins there would be many collisions and recommendations for many users wouldn't make sense, right?

Any help and hints would be appreciated. 
Thanks!
Simon

**Comment by maciejkula** [comment]
Hey!

For the main question:

1. Embedding sizes being too big could easily be a problem. You should exert relatively tight, manual control (say, maximum size of X million) over the size of those, because they are the biggest determinant of the size of your model.
2. `.from_tensor_slices` is also potentially very problematic. Not only does it need your data to be in memory, but also can easily run into TensorFlow graph size limitations.

In general, TensorFlow (and TFRS) are designed to consume datasets streamed from disk. This almost completely decouples your data size from your memory requirements. This also means that vocabularies (and other whole-dataset statistics) are normally created in a separate process ahead of model training.

The common approach for managing embedding size is to use a mix of explicit vocabulary (say, your top 1M users) and hashing (for the remainder). For example, the [StringLookup](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/StringLookup) layer takes an explicit vocabulary, but can also handle anything out-of-vocabulary through hashing.

Side questions:

1. Yes - increasing the batch size is the main way of getting better hardware utilization.
2. As I mentioned above, a mix of explicit vocabularies and hashing is a common approach.

**Comment by SimonCW** [comment]
Hi, 

thank you very much @maciejkula! I implemented your suggestions and they solved my memory problems. It just took a bit of a mindset shift from the "everything in memory" style of working with LightFM. I now have a job that precomputes the vocabularies and some common statistics such as number of interactions (or inferring them from parquet meta-data). Also, I had quite some problems with streaming parquet from S3 via tensorflow-io. Changing to a pre-processing job and storing all the interaction data on EBS helped and streaming from there made everything much easier. 

Thanks, I'll close this!

**Comment by maciejkula** [comment]
Fantastic, very happy it worked!
