### ISSUE TITLE
[Question] How is the batch for FactorizedTopK loss in retrieval model created?

### ISSUE THREAD

**Issue by drljem** [tensorflow/recommenders#452]
Hi,

In the documentation (https://www.tensorflow.org/recommenders/examples/basic_retrieval) we see that the the negatives for the loss function based on FactorizedTopK  are sampled from a batch of data (of size 128):

> To do this, we can use the tfrs.metrics.FactorizedTopK metric. The metric has one required argument: the dataset of candidates that are used as implicit negatives for evaluation.
> 
> ```
> metrics = tfrs.metrics.FactorizedTopK(`
> candidates=movies.batch(128).map(movie_model))
> ```

Later on on the same link we see that the model is trained on a larger batch (of size 4096):

>```
>`cached_train = train.shuffle(100_000).batch(8192).cache()`
>`cached_test = test.batch(4096).cache()`
>`model.fit(cached_train, epochs=3)`
>```

My question is how do these two batches interact. Is the first batch (of size 128) used for negatives, sampled from the larger batch of size 4096? Or it is implemented in some other way? 

The reason I am asking is because I am building a recommender for a highly temporal product (the supply changes from day to day). That is why I want full control of what is being sampled as potential negatives - if I am correct to interpret that they are only sampled from the current training batch, I can proceed by generating the batches in appropriate way.

Thanks!

Marin

**Comment by patrickorlando** [comment]
Hey @drljem,

Metrics actually don't affect the model and are calculated only so that we can evaluate the performance of the model against something real that we care about (not just a loss).

What `tfrs.metrics.FactorizedTopK` does is calculate top K categorical accuracy: how often the true candidate is in the top K candidates for a given query.

When it does this it calculates the score between the query and every possible candidate in your dataset, then it checks whether the true item is within the Top K items. When this is averaged over your batch you get top K categorical accuracy.
To do this it has to calculate the candidate embeddings for every item, and that is what `movies.batch(128).map(movie_model))` is doing. The batch size here is simply there to prevent running out of memory.

Negatives used for updating the model weights are sampled from the within the batches of your training dataset `train.shuffle(100_000).batch(8192).cache()`.

Now to your final question. You are not able to control which examples are used as in batch negatives. The dynamics of item availability does make this a tricky problem and I don't have an answer, but here are some thoughts which may or may not be helpful. 

1. You have a smallish number of available items at any time.
Turn this into a ranking problem. You would need to pre-calculate positive and negative pairs of items based on your data and train a Ranking model, then at inference time you calculate the score between the user and all available items on that day. smallish here really means that your model can return a result within some latency requirement. Model complexity and number of items both affect this.

2. You have lots of items, and most are available at any time
You can use the Retrieval model as is, returning a large enough number of items that you can filter out unavailable products in your API and still have results to return.

3. If you have lots of items, and a lot of unavailable items at any time.
Then you might need to use a more featured retrieval index. For example you train your model using the TRFS framework with the regular in batch negative sampling. You export your candidate vectors to something like Elastic Search, which can store the embedding, item metadata and importantly the quantity. When you need to produce a recommendation, you pass the query features into the query model and obtain the query embedding, you then send that in a query to Elastic Search which filters out unavailable items before ranking the results by the dot product score. 

I would start with testing 2. After training you can run some predictions with a large K and test scenarios for out of stock items. If the results look good then you don't need to manually sample negatives. If the K required is not too large then you may be able to proceed with this option. If the K required is too large then you would have to go with 3.

**Comment by drljem** [comment]
Hi @patrickorlando,

Thanks a lot for the explanation and proposed workarounds. I am worried however, that not accounting for the unavailable items is going to bias the estimates. Suppose that you have a user that adores products in category B and is willing to spend much more on them then on products of category A. Suppose, that products of category B are available only 10% of time, and that the user is choosing products from those two categories each day. If I train using the negative sampling as is, the recommender is going to think that user prefers product category A (since 9 times out of 10 he is choosing the product category A, and he doesn't know product B was unavailable), so we will miss out on recommending B products, even when they are available.

I am thinking about triplet loss here - basically we have two vectors in batches, and we want to compare the anchor vector to the positive example, and negative example(s) that are present only in that batch. I am guessing that on top of solving my issue, this would alleviate computational burden? Do you think I could add a custom loss function like this within tf recommenders - any advice or templates on this? Can you see any substantial problems with this approach?

I am giving an example of the loss function I am thinking about below (this one assumes that the positive examples are found in the same tower-rows within a batch).


```
def TripletLossFn(v1, v2, margin=0.25):  
    # take dot product of all vectors in the batch
    scores = fastnp.dot(v1, v2.T)  # pairwise cosine sim
    # calculate new batch size
    batch_size = len(scores)
    # grab positive examples (on the diagonal)
    positive = fastnp.diagonal(scores) 
    # substract 2 from the diagonal to ensure the diagonal terms are not taken as positive examples
    negative_without_positive = scores - 2.0 * fastnp.eye(batch_size)
    # take the maximum by row, to find the highest predicted negative (we could do a top k here)
    closest_negative = negative_without_positive.max(axis=1)
    #calculate the triplet loss
    triplet_loss = fastnp.maximum(0.0, margin - positive + closest_negative)    
    return triplet_loss
```
