### ISSUE TITLE
[Question] How can we implement continuous training for very large dataset ?

### ISSUE THREAD

**Issue by thanhNt16** [tensorflow/recommenders#492]
Hi devs and community members. Firstly, thank you all for introducing this amazing project. I have successfully implemented the model with project tutorial with my small dataset. However, when I come to production version, my dataset is very large (around 81m interaction records and continue to increase each day). I think I could train the model on each smaller chunk of dataset, but I’m not sure it is the right way to keep the model accuracy.
For example:
- If I train the model on chunk1
- After a day, I retrain the model on chunk2
Is the model still working when I tried to predict for a record from chunk1 ?
 Could you suggest me an approach to retrain the model in this scenario ? 
  
I would very appreciate to hear your suggestion. Thank you

**Comment by josealbertof** [comment]
The model trained on chunk1 should keep on working when trained on chunk2 if you make a checkpoint of your model properly. However, you should consider the following.

If you are using the same model from the tutorial, your users and items receive an embedding based on their id. The vocabulary (aka the ids of every user/item) must be given in advance when creating the network. Any unknown ids will be represented by the same embedding (like a "deafult" representation). Therefore, if you train on chunk1 with ONLY the users/items that are present on chunk1, the model will not work as you expect for the user/item ids in chunk2 that were not present in chunk1.

A possible workaround for this is to train on chunk1, but specifying the full vocabulary of all the chunks when creating the model.

**Comment by josealbertof** [comment]
As you say you should save the previous model instead of `tfrs.layers.factorized_top_k.BruteForce(model.user_model)`
This last one is thought to be used on deployment for making inference, which I guess is not what you want at this point.

To save a checkpoint of your model you should call 

`model.save_weights('checkpoint.ckpt')`

If you want to later start from the point where you left your training. Then, you should define the model again and call `model.load_weights('checkpoint.ckpt')` after compiling.

**Comment by pavel-katkov** [comment]
@josealbertof @thanhNt16 Hi! Did it work for you? Do you happen to have an example?
